spring:
  application:
    name: sb3
server:
  port: 8080

logging:
  path: /Users/max/logs
  config: classpath:logback-stdout.xml
  level:
    org.springframework.web.client: WARN

springdoc:
  packagesToScan: api.controller, api.controller2
  api-docs:
    enabled: true   #默认为true开启
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  openapi:  # 我自定义的
    title: 我的xxx api文档
    description: 开发者-jinfeng.hu
    version: 0.1
    license:
      name: Apache 2.0
      url: http://springdoc.org
    externalDocs:
      description: Wiki Documentation
      url: https://springshop.wiki.github.org/docs