spring:
  application:
    name: admin
#  tomcat:
#    remote-ip-header: X-Real-IP
#    protocol-header: X-Forwarded-Proto
#    uri-encoding: UTF-8
#    max-threads: 100
#  servlet:
#    multipart:
#      max-file-size: 10MB
#      max-request-size: 10MB

server:
  port: 8888

mybatis:
  configuration:
    map-underscore-to-camel-case: true

logging:
  path: /Users/max/logs
  config: classpath:logback-stdout.xml
  level:
    tibet: INFO
    org.springframework.web.client: WARN
